# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('x', models.FloatField(db_index=True, default=0.0)),
                ('y', models.FloatField(db_index=True, default=0.0)),
                ('z', models.FloatField(db_index=True, default=0.0)),
                ('w', models.FloatField(default=0.0, verbose_name='width')),
                ('h', models.FloatField(default=0.0, verbose_name='height')),
                ('d', models.FloatField(default=0.0, verbose_name='depth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThingClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('module', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('box', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='world', to='unsccore.Box')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='box',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unsccore.ThingClass'),
        ),
        migrations.AddField(
            model_name='box',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unsccore.Box'),
        ),
        migrations.AddField(
            model_name='bot',
            name='box',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='unsccore.Box'),
        ),
    ]
