# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unsccore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unsccore.Box'),
        ),
        migrations.AlterField(
            model_name='world',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unsccore.Box'),
        ),
    ]
